<a href="https://colab.research.google.com/github/hariThorve/webscrapping/blob/main/01_neuralNetworks_withTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import tensorflow as tf
import numpy as np

In [16]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array([11, 12, 13, 14, 15, 16, 17, 18])

X = tf.constant(X, dtype=tf.float32)
y = tf.constant(y, dtype=tf.float32)

X, y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([11., 12., 13., 14., 15., 16., 17., 18.], dtype=float32)>)

# Steps for modelling in Tensorflow
* **Creating a model**: Define input, Output and Hidden layers of a deep learning model.
* **Compiling a model**: Define the loss function (eg. MSE, MAE, Hybrid) and optimizers (eg. Gradient Descent) and evaluation metrics.
* **Fitting a model**: Letting the model find out patterns between X and y.

In [31]:
# set random seed
tf.random.set_seed(42)

# Create model using Sequential API

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

# Compile the model

model.compile(loss = tf.keras.losses.mae, #mae = Mean absolute error
              optimizer = tf.keras.optimizers.SGD(), #sgd stands for stochasitc gradient descent
              metrics = ["mae"]
              )

# Fit the model
X = tf.reshape(X, [-1, 1])
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 17.7233 - mae: 17.7233
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 17.5108 - mae: 17.5108
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 17.2983 - mae: 17.2983
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 17.0858 - mae: 17.0858
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 16.8733 - mae: 16.8733
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 16.6608 - mae: 16.6608
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 16.4483 - mae: 16.4483
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 16.2358 - mae: 16.2358
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 16.0233 - mae: 16.0233
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 15.8108 - mae: 15.8108
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 15.5983 - mae: 15.5983
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 15.3858 - mae: 15.3858
Epoch 13/100
1/1 ━━━━━━━━━━

In [32]:
model.predict(tf.constant([9.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[23.590843]], dtype=float32)